spring.application.name=contact

server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/contact_db
spring.datasource.username=root
spring.datasource.password=chen919191

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
