spring.application.name=Contact1
spring.datasource.url=jdbc:mysql://localhost:3306/contact_sys_db
spring.datasource.username=root
spring.datasource.password=chen919191

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secret=ZHVtbXktc3RhYmxlLXNlY3JldC1rZXktbXVzdC1iZS1sb25n
